-- Migration: grant read-only access for backend_reader role on indexer-owned tables.
--
-- This was previously embedded in db/baseline-schema.sql but does not belong there.
-- The baseline is machine-generated by `pnpm db:check-drift -- --update-baseline`
-- and is overwritten on every refresh; hand-written SQL must live in a migration.
--
-- Run order: apply this AFTER the indexer TypeORM migrations that create the
-- `raffle` and `participant` tables so the GRANT targets exist.

DO $$
DECLARE
    t text;
    indexer_tables text[] := ARRAY['raffle', 'participant'];
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'backend_reader') THEN
        CREATE ROLE backend_reader NOLOGIN;
    END IF;

    GRANT USAGE ON SCHEMA public TO backend_reader;

    FOREACH t IN ARRAY indexer_tables
    LOOP
        IF EXISTS (
            SELECT 1 FROM pg_tables
            WHERE schemaname = 'public' AND tablename = t
        ) THEN
            EXECUTE format('REVOKE ALL PRIVILEGES ON TABLE public.%I FROM backend_reader', t);
            EXECUTE format('GRANT SELECT ON TABLE public.%I TO backend_reader', t);
        END IF;
    END LOOP;
END $$;
