apiVersion: v1
kind: Service
metadata:
  name: tikka-backend
  namespace: tikka
  labels:
    app: tikka-backend
spec:
  selector:
    app: tikka-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
