apiVersion: v1
kind: Service
metadata:
  name: tikka-indexer
  namespace: tikka
  labels:
    app: tikka-indexer
spec:
  selector:
    app: tikka-indexer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
