-- Baseline schema for Tikka platform
-- Generated by: npm run db:check-drift -- update-baseline
-- 
-- This file represents the expected schema after running ALL committed
-- migrations (backend, indexer, oracle) against a fresh PostgreSQL instance.
--
-- IMPORTANT: Update this file whenever a schema-changing migration is merged.
--   1. Merge the migration PR
--   2. Run: npm run db:check-drift -- update-baseline
--   3. Commit the updated baseline-schema.sql
--
-- CI will reject PRs that cause drift between this baseline and a fresh
-- migration run. If CI fails with a drift error on a migration PR, run the
-- update command above and push the baseline change as part of your PR.

-- Enforce read-only access from backend to indexer-owned tables.
--
-- Table names are sourced directly from the @Entity(...) decorators in
-- indexer/src/database/entities/.  Update this list whenever a new entity
-- is added to that directory (see docs/database/ENTITY_OWNERSHIP.md).
DO $$
DECLARE
    tbl text;
    indexer_tables text[] := ARRAY[
        'raffles',
        'tickets',
        'users',
        'raffle_events',
        'platform_stats',
        'platform_state',
        'indexer_cursor',
        'dead_letter_events',
        'webhooks',
        'webhook_deliveries',
        'webhook_dead_letter_deliveries',
        'archive_checkpoints'
    ];
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'backend_reader') THEN
        CREATE ROLE backend_reader NOLOGIN;
    END IF;

    GRANT USAGE ON SCHEMA public TO backend_reader;

    FOREACH tbl IN ARRAY indexer_tables
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = tbl
        ) THEN
            RAISE WARNING 'backend_reader grant: table public.% does not exist — skipping. '
                          'Run migrations before applying this baseline.',
                          tbl;
            CONTINUE;
        END IF;

        EXECUTE format('REVOKE ALL PRIVILEGES ON TABLE public.%I FROM backend_reader', tbl);
        EXECUTE format('GRANT SELECT ON TABLE public.%I TO backend_reader', tbl);
    END LOOP;
END $$;