-- refresh_tokens: persistent storage for hashed refresh tokens
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_address TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_address ON refresh_tokens(user_address);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_revoked ON refresh_tokens(revoked);

ALTER TABLE refresh_tokens ENABLE ROW LEVEL SECURITY;
-- Access to this table should only be via the backend service_role key.

COMMENT ON TABLE refresh_tokens IS 'Hashed refresh tokens for rotating refresh-token flows';
COMMENT ON COLUMN refresh_tokens.user_address IS 'Stellar wallet address of token owner';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'HMAC-SHA256 hash of the refresh token';
COMMENT ON COLUMN refresh_tokens.revoked IS 'Flag indicating token revocation';
COMMENT ON COLUMN refresh_tokens.created_at IS 'Creation timestamp';
COMMENT ON COLUMN refresh_tokens.updated_at IS 'Last update timestamp';
COMMENT ON COLUMN refresh_tokens.last_used_at IS 'Last time the token was used to refresh';
COMMENT ON COLUMN refresh_tokens.expires_at IS 'Expiration timestamp for the refresh token';
