-- siws_nonces: persistent storage for SIWS nonces to prevent replay attacks
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS siws_nonces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address TEXT NOT NULL,
  nonce TEXT NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Replay protection: same nonce cannot be reused for the same address
  UNIQUE(address, nonce)
);

CREATE INDEX IF NOT EXISTS idx_siws_nonces_address ON siws_nonces(address);
CREATE INDEX IF NOT EXISTS idx_siws_nonces_expires_at ON siws_nonces(expires_at);

ALTER TABLE siws_nonces ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE siws_nonces IS 'Nonces issued for SIWS authentication';
COMMENT ON COLUMN siws_nonces.address IS 'Stellar wallet address requesting the nonce';
COMMENT ON COLUMN siws_nonces.nonce IS 'The random nonce string';
COMMENT ON COLUMN siws_nonces.issued_at IS 'Timestamp when the nonce was issued';
COMMENT ON COLUMN siws_nonces.expires_at IS 'Expiration timestamp for the nonce';
COMMENT ON COLUMN siws_nonces.consumed IS 'Flag indicating if the nonce has been used for successful verification';
