apiVersion: v1
kind: Service
metadata:
  name: tikka-oracle
  namespace: tikka
  labels:
    app: tikka-oracle
spec:
  selector:
    app: tikka-oracle
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
